### ISSUE TITLE
Tolerance / precision behavior seems wrong

### ISSUE THREAD

**Issue by rvdbijl** [swingerman/ha-dual-smart-thermostat#10]
In heating mode, if I have the tolerance set to 1F and the precision to 0.1F, and the setpoint to 68F, it turns on at 66.9F, but turns off right away when it gets to 67.1F. I would expect it to turn on at 66.9F, and turn off at 68F.

**Comment by KixAss** [comment]
Same issue here.

**Comment by KixAss** [comment]
@rvdbijl You can fix it by changing 2 lines in climate.py:

Line 988:
return target_temp >= self._cur_temp + 0 if self._is_heter_active else self._cold_tolerance

Line 993:
return self._cur_temp >= target_temp + 0 if self._is_cooler_active else self._hot_tolerance

**Comment by swingerman** [comment]
Could you guys please post your configuration here? I cannot reproduce the problem

**Comment by micksam7** [comment]
Same problem here. This seems to only occur when in dual Heat/Cool mode. In normal Heat or normal Cool mode, it behaves as expected.

```
climate:
  - platform: dual_smart_thermostat
    name: Adv Basement Heatpump
    heater: input_boolean.basement_heatpump_heat
    cooler: input_boolean.basement_heatpump_cool
    target_sensor: sensor.average_basement_temperature
    target_temp: 70
    target_temp_high: 71
    target_temp_low: 69
    cold_tolerance: .5
    hot_tolerance: .5
    min_cycle_duration:
      seconds: 60
    keep_alive:
      minutes: 3
    precision: 0.1
```

![image](https://user-images.githubusercontent.com/5876099/196382187-df66a441-0396-4755-9ef3-d04fbb17c52d.png)


Changing the climate.py lines as referenced in KixAss's comment partly fixes, but heats/cools only to the set point.
