### ISSUE TITLE
 The preset_mode is not a valid preset_mode:

### ISSUE THREAD

**Issue by serlinGi** [swingerman/ha-dual-smart-thermostat#103]
hi,
at restart of homeassistant or reload configuration with developer tools (section yaml) I get this **error** in log ( and in popup on the screen with thermostat cards):

_"Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:282
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:21:43 (40 occurrences)
Last logged: 12:22:04
[139861757342400] The preset_mode is not a valid preset_mode: none, away, comfort, home, sleep"_

I think (I'm almost sure) it only appeared after latest HA update.

at tame time I get this **warning**:
_"Entity None (<class 'custom_components.dual_smart_thermostat.climate.DualSmartThermostat'>) implements HVACMode(s): off, heat, cool, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/swingerman/ha-dual-smart-thermostat/issues"_

My conf:
Homeassistant.OS 
Core 2024.2.1
Supervisor 2024.01.1
Operating System 11.5
Frontend 20240207.1

Thx for your job

**Comment by swingerman** [comment]
Thanks for finding this. I will look into this as son as possible

**Comment by swingerman** [comment]
could you please provide your configuration?

**Comment by serlinGi** [comment]
> could you please provide your configuration?

I?  Yes, of course

```
climate:
#
  - platform: dual_smart_thermostat
    name: "climatizzatore cucina"
    unique_id: climate.climatizzatore_cucina
    heater: switch.clima_cucina
    cooler: input_boolean.switch_virtuale_clima 
    target_sensor: sensor.aqara_cucina_temperature
    openings: 
      - entity_id: binary_sensor.veranda_cucina_contact
        timeout: 00:03:00
    heat_cool_mode: true # <-important
    initial_hvac_mode: "heat" #"heat_cool"
    ac_mode: false
    min_temp: 16
    max_temp: 30
    target_temp: 21.5
    target_temp_high: 25
    target_temp_low: 21
    cold_tolerance: 0.4
    hot_tolerance: 0.1
    target_temp_step: 0.1
    min_cycle_duration:
      minutes: 1
    away: 
      temperature: 15
      target_temp_low: 16
      target_temp_high: 28
    home: 
      temperature: 22
      target_temp_low: 22.5
      target_temp_high: 25.5
    comfort: 
      temperature: 21.5
      target_temp_low: 22
      target_temp_high: 26
    sleep: 
      temperature: 19.5
      target_temp_low: 20.0
      target_temp_high: 27
#
```

It' s OK?

**Comment by serlinGi** [comment]
hi, 
only now (because after a restart the error did not appear and I did further tests) thinking about everything, I realized something: the error message appears only if at the same time as the restart I'm viewing the thermostat card.

the warning message instead appears in every situation.

could it be a problem with the cards?  

Anyway, everything works fine

this is the card
```
features:
  - type: climate-hvac-modes
    hvac_modes:
      - 'off'
      - heat
      - cool
      - heat_cool
  - type: climate-preset-modes
    style: dropdown
    preset_modes:
      - none
      - away
      - comfort
      - home
      - sleep
  - type: target-temperature
type: tile
entity: climate.climatizzatore_oblo
name: Oblò
vertical: false
state_content:
  - current_temperature
  - hvac_action
icon: mdi:sun-snowflake-variant
```
