### ISSUE TITLE
[bug] - min_cycle_duration ignored

### ISSUE THREAD

**Issue by coltography** [swingerman/ha-dual-smart-thermostat#12]
When setting min_cycle_duration to either seconds: 120 or minutes: 2 I get the same results with my cooling turning off/on every few seconds if the temperature is close to the setpoint. 

Is there something I'm missing? I copied it straight from the example config and it still doesn't work as intended.

**Comment by swingerman** [comment]
PLease let us know if v0.7.0 fixed it.

**Comment by alvarocarrera** [comment]
Thanks a lot, @ollo69 but I have checked the min_cycle_duration is not working since v0.6.7.

Asap the temp reaches the target, it stops without checking the min_cycle_duration configuration. I checked with v0.7.0 and v0.7.1

**Comment by alvarocarrera** [comment]
No... I have tested a bit more, during this last night (a quite cold night). The result is that it is not working at all. :cry: One of the cycles was only 10 minutes, other only 35 minutes, when I have the following configuration in all my thermostats: 
```
min_cycle_duration:                                                                          
    hours: 1                                                                                   
    minutes: 30                                                                                
    seconds: 0                                                                                 
    milliseconds: 0 
```

I will try to debug this problem during the weekend.

**Comment by mat1990dj** [comment]
Same for me, I have a min cycle of 30 seconds and it completely ignores it

**Comment by swingerman** [comment]
I couldn't reproduce it with your setup, and the latest release is 0.9.8.2 @drulia .
Closing for now. Feel free to reopen if you still see this issue.

**Comment by mat1990dj** [comment]
This setup:
```

  - platform: dual_smart_thermostat
    name: Basement
    unique_id: basement
    heater: input_boolean.heat_request_basement
    cooler: input_boolean.cool_request_basement
    target_sensor: sensor.basement_temperatura
    humidity_sensor: sensor.basement_humedad
    heat_cool_mode: false
    target_temp: 75
    initial_hvac_mode: "off"
    min_temp: 60
    max_temp: 85
    precision: 1
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    **min_cycle_duration:
      seconds: 30**
    keep_alive:
      minutes: 10
```

I change the temperature at 12:41:05 and then at 12:41:06

It turns on at 12:41:05
![image](https://github.com/user-attachments/assets/3a06f86a-2d55-4001-a88c-36971de7c709)
and off one second later:
![image](https://github.com/user-attachments/assets/ef0e675b-f8aa-4c86-a51d-049b0f7dcc4c)

The heater entity:
![image](https://github.com/user-attachments/assets/93b3db20-f8bc-4767-b8c6-71fc389d1603)

I would expect it to wait 30 seconds until it turns off the heat request.
