### ISSUE TITLE
[FEAT] - heat pump mode (dual with only one switch)

### ISSUE THREAD

**Issue by swingerman** [swingerman/ha-dual-smart-thermostat#143]
Many users have a problem using the component in dual mode with a heat pump with only one switch, and the heat pump switches to heat or cool.

Possible solution:

- introduce a boolean input (switch) that reverses the HVAC action
- if this is set, then allow using the same switch for both the heater and the cooler
- in this case, this setup will need the following configuration values set:
- - heater
- - cooler
- - heat_cool_mode: true
- - heat_cool_reverse_entity

**Comment by Smittybk1** [comment]
To add to this, My system requires the fan operate in both heating and cooling mode. There is a Fan_with_ac option, I also need a Fan_with_heater option

**Comment by cputoaster** [comment]
Would the boolean input switch be able to directly connect to a binary sensor? My heat pump exposes a "binary_sensor.status_cooling_43024" that would need to be somehow used by the heat_cool_reverse_entity configuration value.

**Comment by swingerman** [comment]
Yes. In the implementation, the switch can be a boolean input. Either manual or direct inout from the heat pump.

**Comment by swingerman** [comment]
Update: I am happy to inform you that I implemented a working version of the heat pump mode. Now, I have to cover all with tests to ensure the feature is hard enough to let you try it out.

In heat_pump mode, there will be a maximum three HVAC modes available based on the current mode of the heat pump and if dual mode is enabled:

## Dual mode
**heating** _(is_heat_pump: false)_:
- heat/cool
- heat
- off

**cooling** _(is_heat_pump_cooling: true)_:
- heat/cool
- heat
- off

## Single mode
**heating** _(is_heat_pump: false)_:
- heat
- off

**cooling** _(is_heat_pump_cooling: true)_:
- heat
- off

**Comment by Matz88** [comment]
Hi, do i understand correctly that this fix will also allow to set the same entity for cooler and heater?
See #255

**Comment by swingerman** [comment]
Exactly!

**Comment by RaxCore** [comment]
Hi, I was looking for that feature, too - thanks! Unfortunately I don´t get it running. The same entity for cooler and heater throws an error:
![grafik](https://github.com/user-attachments/assets/70678f6d-3ae5-4084-b61c-f21ff6304da8)
This is my config:
```
# --------- Arbeitszimmer DUAL--------- #    
  - platform: dual_smart_thermostat
    name: Dual Thermostat Arbeitszimmer
    unique_id: Dual_Thermostat_Arbeitszimmer
    heater: switch.shmini_arbeitszimmer_switch_0
    cooler: switch.shmini_arbeitszimmer_switch_0
    target_sensor: sensor.klima_arbeitszimmer_temperature
    heat_cool_mode: true # <-required
    initial_hvac_mode: "off"    
    min_temp: 15
    max_temp: 25
    target_temp: 22
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    min_cycle_duration:
      seconds: 5
    precision: 0.1 
```
What I'm doing wrong?

**Comment by swingerman** [comment]
> Hi, I was looking for that feature, too - thanks! Unfortunately I don´t get it running. The same entity for cooler and heater throws an error: ![grafik](https://private-user-images.githubusercontent.com/96478711/350725886-70678f6d-3ae5-4084-b61c-f21ff6304da8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzE3NTMsIm5iZiI6MTcyMTYzMTQ1MywicGF0aCI6Ii85NjQ3ODcxMS8zNTA3MjU4ODYtNzA2NzhmNmQtM2FlNS00MDg0LWI2MWMtZjIxZmY2MzA0ZGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA2NTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ODQxNGVjZDc4NTRmMDVjOGMzYjJiMGIxNDY5MWY0NzdkODBhZGEwNDJlNjFhODJjN2ViMTg2Mjc1NzZmMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Rs6ybkM1MBFjvbsLuyAhftsAk9zDWpnh5r_ei3c4Is) This is my config:
> 
> ```
> # --------- Arbeitszimmer DUAL--------- #    
>   - platform: dual_smart_thermostat
>     name: Dual Thermostat Arbeitszimmer
>     unique_id: Dual_Thermostat_Arbeitszimmer
>     heater: switch.shmini_arbeitszimmer_switch_0
>     cooler: switch.shmini_arbeitszimmer_switch_0
>     target_sensor: sensor.klima_arbeitszimmer_temperature
>     heat_cool_mode: true # <-required
>     initial_hvac_mode: "off"    
>     min_temp: 15
>     max_temp: 25
>     target_temp: 22
>     cold_tolerance: 0.3
>     hot_tolerance: 0.3
>     min_cycle_duration:
>       seconds: 5
>     precision: 0.1 
> ```
> 
> What I'm doing wrong?

The feature is not released yet. Please stay tuned, I need to write a lot of test to make sure it's stable.

**Comment by swingerman** [comment]
Please check and enjoy https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.8.beta-1


### Heat Pump (one switch heat/cool) mode

This setup allows you to use a single switch for both heating and cooling. To enable this mode you define only a single switch for the heater and set the set youer heat pump's current state (heating or cooling) as for the [`heat_pump_cooling`](#heat_pump_cooling) attribute. This must be an entity id of a sensor that has a state of `heating` or `cooling`.

The entity can be an input buulean for manual control or  an entity that provided by the heat pump.

```yaml
heater: switch.study_heat_pump
target_sensor: sensor.study_temperature
heat_pump_cooling: sensor.study_heat_pump_state
```

#### Heat Pump Hvac Modes

##### Heat-Cool Mode

```yaml
heater: switch.study_heat_pump
target_sensor: sensor.study_temperature
heat_pump_cooling: sensor.study_heat_pump_state
heat_cool_mode: true
```

**heating** _(heat_pump_cooling: false)_:
- heat/cool
- heat
- off

**cooling** _(heat_pump_cooling: true)_:
- heat/cool
- cool
- off

##### Single mode

```yaml
heater: switch.study_heat_pump
target_sensor: sensor.study_temperature
heat_pump_cooling: sensor.study_heat_pump_state
heat_cool_mode: false # <-- or not set
```

**heating** _(heat_pump_cooling: false)_:
- heat
- off

**cooling** _(heat_pump_cooling: true)_:
- cool
- off
