### ISSUE TITLE
[bug]. wrong HVACAction is set.

### ISSUE THREAD

**Issue by skarcha** [swingerman/ha-dual-smart-thermostat#144]
I got this error message on logs during Home Assistant start up.

Anyway it "works", but show it's cooling instead of heating...

![imagen](https://github.com/swingerman/ha-dual-smart-thermostat/assets/180601/06b4c8eb-483b-4909-84b3-57cc0619ea80)

**Comment by swingerman** [comment]
Have you tried the latest beta version?

**Comment by skarcha** [comment]
I've just tried it. The error message disappeared, but still showing cooling instead of heating:
![imagen](https://github.com/swingerman/ha-dual-smart-thermostat/assets/180601/f906ea20-9802-424a-b4dd-85e5cbef15a4)

**Comment by swingerman** [comment]
Could you share your yaml config for this thermostat?

**Comment by skarcha** [comment]
Sure!

```yaml
- platform: dual_smart_thermostat
  name: Termostato salón
  heater: switch.rejilla_salon
  cooler: switch.rejilla_ac_salon
  target_sensor: sensor.salonlamparas_salon_temperatura
  heat_cool_mode: true
  min_temp: 18
  max_temp: 26
  initial_hvac_mode: "heat_cool"
```

**Comment by skarcha** [comment]
Is just showing that it's cooling, but it's heating actually.

**Comment by swingerman** [comment]
Thanks.

**Comment by swingerman** [comment]
We determine the current action based on the device state (switch state). For some reason, your cooler seems to be still in the `ON` state.
Are you using a real switch or it's a template switch?

**Comment by skarcha** [comment]
Mmmm... I think you nailed it, because both are template switches, using the same cover:

```yaml
  switches:
    rejilla_salon:
      friendly_name: "rejilla salón Switch"
      value_template: "{{ is_state('cover.openzone_damper_1', 'open') }}"
      turn_on:
        service: cover.open_cover
        data:
          entity_id: cover.openzone_damper_1
      turn_off:
        service: cover.close_cover
        data:
          entity_id: cover.openzone_damper_1

    rejilla_ac_salon:
      friendly_name: "rejilla AC Salón Switch"
      value_template: "{{ is_state('cover.openzone_damper_1', 'open') }}"
      turn_on:
        service: cover.set_cover_position
        data:
          entity_id: cover.openzone_damper_1
      turn_off:
        service: cover.close_cover
        data:
          entity_id: cover.openzone_damper_1
```

I've just modified them to this:

```yaml
  switches:
    rejilla_salon:
      friendly_name: "rejilla salón Switch"
      value_template: "{{ state_attr('cover.openzone_damper_1', 'current_position') == 100 }}"
      turn_on:
        service: cover.open_cover
        data:
          entity_id: cover.openzone_damper_1
      turn_off:
        service: cover.close_cover
        data:
          entity_id: cover.openzone_damper_1

    rejilla_ac_salon:
      friendly_name: "rejilla AC Salón Switch"
      value_template: "{{ state_attr('cover.openzone_damper_1', 'current_position') == 99 }}"
      turn_on:
        service: cover.set_cover_position
        data:
          entity_id: cover.openzone_damper_1
          position: 99
      turn_off:
        service: cover.close_cover
        data:
          entity_id: cover.openzone_damper_1
```

And it works like a charm!

![imagen](https://github.com/swingerman/ha-dual-smart-thermostat/assets/180601/602c76ba-dd0f-43e3-b02f-8b35a651ed16)

![imagen](https://github.com/swingerman/ha-dual-smart-thermostat/assets/180601/50835b27-c1a8-44e8-bdf6-ebc9b9acc3cf)

Thank you very much for your time! Really appreciate it.
