### ISSUE TITLE
Appreciation, question (help) and some ideas

### ISSUE THREAD

**Issue by Bergoglio** [swingerman/ha-dual-smart-thermostat#153]
Good afternoon,

at first : congratulations, this thermostat is a great job (user side) !

I have one question : 
I need to take from the thermostat the two target temperatures (one for heating and one for cooling); in the Home Assistant Generic Thermostat I use this code in sensors.yaml
```
- platform: template
  sensors:
    raffreddamento_nonna_bagno:
      friendly_name: "Target raffreddamento bagno Nonna"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('climate.bagno_freddo_nonna', 'temperature') }}"
```
and
```
- platform: template
  sensors:
    riscaldamento_nonna_bagno:
      friendly_name: "Target riscaldamento bagno Nonna"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('climate.caldo_bagno_nonna', 'temperature') }}"
```
because I settled two thermostat for every room, one for heating and one for cooling.
Instead in ha-dual-smart-thermostat (where there will be only one thermostat for every room), how can I take the two different target temperatures ?

Then, some ideas :

1. I saw that You create a file en.json inside translations, why ? I can translate it into Italian, if is helpful
2. Some terms in the preset names remain in english, is it possible to make an interface fully localized ?
3. The anti-freeze preset is quite misleading (freeze reminds to heating, not cooling); by my point of view probably is better "anti-lock"
4. To manage Openings, is it possible to define if the switch is on when the window/door is closed ? For example I have normal alarm sensors on openings (normally closed) linked to shelly relè and so they tells on when the opening is closed. To solve this I made reverse sensors in Home Assistant, but it will be more comfortable to set a parameter in Dual-Smart-Thermostat

Best regards
