### ISSUE TITLE
[feeat] Opennings only for Heater or Cooler

### ISSUE THREAD

**Issue by milandzuris** [swingerman/ha-dual-smart-thermostat#155]
Hi, there is chance add feature Openings only work for Heater?, i like something like this.
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/4879c12b-0a59-41e6-a6c7-6f5c5ce46fb2)

**Comment by milandzuris** [comment]
> We can do that

Thank you very much, i would really like it if it were because now it's already very hot and I can't use this Thermostat even if I want to.

**Comment by swingerman** [comment]
I am implementing this in a more flexible way.

Instead of setting the heater/cooler, you will be able to set a list of HVAC modes you want to be affected by the openings.

Currently:

* cool
* heat
* fan_only
* heat_cool

**Comment by milandzuris** [comment]
> I am implementing this in a more flexible way.
> 
> Instead of setting the heater/cooler, you will be able to set a list of HVAC modes you want to be affected by the openings.
> 
> Currently:
> 
> * cool
> * heat
> * fan_only
> * heat_cool

thx, can i ask when the beta will be?

**Comment by swingerman** [comment]
Just now:
[v0.9.6.beta-3](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.6.beta-3)

Note you need to provide a list of modes even if just one mode is set.

```yaml
openings_scope:
  - heat
  - cool
```

**Comment by milandzuris** [comment]
> Just now: [v0.9.6.beta-3](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.6.beta-3)
> 
> Note you need to provide a list of modes even if just one mode is set.
> 
> ```yaml
> openings_scope:
>   - heat
>   - cool
> ```

thx but now all my thermostats are heaters why?

**Comment by milandzuris** [comment]
Failed to call service climate/set_hvac_mode. '>=' not supported between instances of 'NoneType' and 'float'

**Comment by milandzuris** [comment]
Failed to call service climate/set_hvac_mode. expected HVACMode or one of 'off', 'heat', 'cool', 'heat_cool', 'auto', 'dry', 'fan_only' for dictionary value @ data['hvac_mode']

**Comment by milandzuris** [comment]
i don't have cool mode, and off mode is totally other, everything was working fine before the new beta version.
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/f2575b65-9f35-4055-95b5-2f107d044f07)
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/9afd91ae-4392-44e8-83f7-ab0a729000bd)
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/9111c86d-8399-4ece-b35c-58328ffe8523)

**Comment by milandzuris** [comment]
@swingerman

**Comment by swingerman** [comment]
Please check [v0.9.6.beta-4](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.6.beta-4)

**Comment by milandzuris** [comment]
same problem when i change to off show me this two temperature for set, but now i have cooler mode, question why i have Heat/Cool mode?
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/8f800142-9ede-4a27-a623-c522fb40e32e)
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/2129add8-5905-451b-a83a-67173c404cb1)

> Please check [v0.9.6.beta-4](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.6.beta-4)

**Comment by swingerman** [comment]
If you set both heater and cooler, we assume you should have heat/cool mode.
Or is this something you don't want?

**Comment by milandzuris** [comment]
> Or is this something you don't want?

no

**Comment by swingerman** [comment]
Ok. Stay tuned.
I will fine tune it that way.

**Comment by milandzuris** [comment]
now i testing set climate temperature from Node-RED i see this problem when i change from NR to 24temp my thermostat change to 20.5, this problem i dont have on generic thermostat problem is in {"temperature":24.0} need set to {"temperature":24}

and other problem thermostat is not heating (stop working)

https://github.com/swingerman/ha-dual-smart-thermostat/issues/170

![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/5dca5b12-4cb1-49ad-9483-56666f930ebb)
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/445feac2-ff24-44a7-9ec9-5ce2e783993a)
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/3e7df702-e42c-4fa4-ae68-76e9bf016d8d)
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/22ce1d85-c41d-401f-8bec-734dcd2a6634)

**Comment by milandzuris** [comment]
My current cfg

```
  - platform: dual_smart_thermostat
    name: Bedroom Thermostat
    unique_id: Bedroom Thermostat
    heater: switch.bedroom_radiator
    cooler: fan.bedroom_fan
    target_sensor: sensor.bedroom_temperature
    openings:
      - binary_sensor.bedroom_window
      - binary_sensor.bedroom_second_window
    openings_scope:
      - heat
    min_temp: 18
    max_temp: 27
    target_temp: 23.0
    hot_tolerance: 0
    cold_tolerance: 0.20
    precision: 0.1
    target_temp_step: 0.5
    initial_hvac_mode: heat
```
