### ISSUE TITLE
Thermostat no longer turns on to heat/cool mode

### ISSUE THREAD

**Issue by andrew-kennedy** [swingerman/ha-dual-smart-thermostat#167]
I used to use google assistant to send "turn on" to the thermostat which would turn it from "off" mode into "heat/cool" mode, now after updating to the latest beta it turns only to cool mode or heat mode, I think the problem may stem from this commit: https://github.com/swingerman/ha-dual-smart-thermostat/commit/b448cfa2eae5fb73599c9171c3b9f807fd4843bb.

I think whatever "internal" mode heat/cool mode is set to last (cooling or heating) is what becomes the mode on next thermostat power on, but I'm not sure yet.

I never turn it out of heat/cool mode, so I'm not sure how it ends up powering on not in that mode.

**Comment by swingerman** [comment]
Which version do you currently use?

**Comment by swingerman** [comment]
Could you please share your configuration?

**Comment by andrew-kennedy** [comment]
```
climate:
  - platform: dual_smart_thermostat
    name: Eight Sleep Thermostat
    unique_id: eight_sleep_thermostat
    heater: switch.eight_sleep_heat_power_switch
    cooler: switch.eight_sleep_cool_power_switch
    target_sensor: sensor.andrew_s_bed_temperature
    min_temp: 55
    max_temp: 110
      #inital_hvac_mode: "heat_cool"
    heat_cool_mode: true
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    #min_cycle_duration:
      #minutes: 5
    precision: 1.0

switch:
  - platform: template
    switches:
      eight_sleep_cool_power_switch:
        unique_id: eight_sleep_cool_power_switch
        friendly_name: "Eight Sleep Cool Power Switch"
        value_template: "{{ (not is_state('sensor.andrew_s_bed_state_type', 'off')) and (int(states('sensor.andrew_s_bed_temperature')) > (state_attr('climate.eight_sleep_thermostat', 'target_temp_high') + state_attr('climate.eight_sleep_thermostat', 'target_temp_low') / 2)) }}"
        turn_on:
          service: script.eight_sleep_set_temperature_from_ha_climate_entity
        turn_off:
          service: script.eight_sleep_thermostat_mode_handoff
          data:
            script_caller: switch.eight_sleep_cool_power_switch
      eight_sleep_heat_power_switch:
        unique_id: eight_sleep_heat_power_switch
        friendly_name: "Eight Sleep Heat Power Switch"
        value_template: "{{ (not is_state('sensor.andrew_s_bed_state_type', 'off')) and (int(states('sensor.andrew_s_bed_temperature')) < (state_attr('climate.eight_sleep_thermostat', 'target_temp_high') + state_attr('climate.eight_sleep_thermostat', 'target_temp_low') / 2)) }}"
        turn_on:
          service: script.eight_sleep_set_temperature_from_ha_climate_entity
        turn_off:
          service: script.eight_sleep_thermostat_mode_handoff
          data:
            script_caller: switch.eight_sleep_heat_power_switch
```

And here's the service config that is called when the heater/cooler are "turned on":

```
alias: Eight Sleep Set Temperature From HA Climate Entity
sequence:
  - service: script.eight_sleep_set_temperature
    data:
      target: >-
        {{ ((state_attr('climate.eight_sleep_thermostat', 'target_temp_low') +
        state_attr('climate.eight_sleep_thermostat', 'target_temp_high')) // 2)
        }}
      duration: 28800
mode: single
icon: mdi:script
```

which calls:

```
alias: Eight Sleep Set Temperature
sequence:
  - service: eight_sleep.heat_set
    data:
      sleep_stage: current
      duration: "{{ duration }}"
      target: >-
        {% from 'fahrenheit_to_raw.jinja' import fahrenheit_to_raw %} {{
        fahrenheit_to_raw(target) }}
    target:
      entity_id: sensor.andrew_s_bed_temperature
  - service: eight_sleep.heat_set
    data:
      sleep_stage: bedTimeLevel
      duration: "{{ duration }}"
      target: >-
        {% from 'fahrenheit_to_raw.jinja' import fahrenheit_to_raw %} {{
        fahrenheit_to_raw(target) }}
    target:
      entity_id: sensor.andrew_s_bed_temperature
  - service: eight_sleep.heat_set
    data:
      sleep_stage: initialSleepLevel
      duration: "{{ duration }}"
      target: >-
        {% from 'fahrenheit_to_raw.jinja' import fahrenheit_to_raw %} {{
        fahrenheit_to_raw(target) }}
    target:
      entity_id: sensor.andrew_s_bed_temperature
  - service: eight_sleep.heat_set
    data:
      sleep_stage: finalSleepLevel
      duration: "{{ duration }}"
      target: >-
        {% from 'fahrenheit_to_raw.jinja' import fahrenheit_to_raw %} {{
        fahrenheit_to_raw(target) }}
    target:
      entity_id: sensor.andrew_s_bed_temperature
mode: single
icon: mdi:home-thermometer
fields: {}
```
