### ISSUE TITLE
[Bug?] Set temps don't restore on HA boot if a preset is set when HA restarts

### ISSUE THREAD

**Issue by T3chArmy** [swingerman/ha-dual-smart-thermostat#184]
Defaults to my min and max range of thermostat. This error also gets thrown. I'm guessing there is an issue restoring settings correctly at startup.

```
This error originated from a custom integration.

Logger: custom_components.dual_smart_thermostat.hvac_device.cooler_fan_device
Source: custom_components/dual_smart_thermostat/hvac_device/cooler_fan_device.py:163
integration: dual_smart_thermostat (documentation, issues)
First occurred: 22:55:56 (19 occurrences)
Last logged: 22:57:50

Invalid HVAC mode: None
```

Here's my config:

```
climate:
  - platform: dual_smart_thermostat
    name: Hallway Thermostat
    unique_id: hallway_thermostat
    heater: switch.thermostat_controller_l1
    cooler: switch.thermostat_controller_l2
    fan: switch.thermostat_controller_l3
    target_sensor: sensor.average_house_temperature
    openings:
        - binary_sensor.office_window_contact
    min_temp: 60
    max_temp: 85
    fan_hot_tolerance: 0.5
    heat_cool_mode: true
    min_cycle_duration:
      seconds: 60
    keep_alive:
      minutes: 3
    away:
      target_temp_low: 68
      target_temp_high: 77
    home:
      target_temp_low: 71
      target_temp_high: 74
    precision: 0.1
    target_temp_step: 0.5
``` 

If HA is restarted in Preset None, then temperatures are restored correctly.
