### ISSUE TITLE
disable Heat/Cool Mode

### ISSUE THREAD

**Issue by mbrevda** [swingerman/ha-dual-smart-thermostat#215]
Is it possible to (add an option to) disable Heat/Cool Mode? I.e. the thermostat should support heat _or_ cool, but not Heat/Cool? Thanks!

**Comment by swingerman** [comment]
Yes. If you don't set heat_cool_mode: true. Exactly that should happen.

**Comment by mbrevda** [comment]
Thanks! It seems the climate entity is nevertheless being set with a `target_temp_low` and a `target_temp_high` attribute, causing the thermostat to have two temperatures (although no heat/cool mode). Can that be disabled, too?

<img width="475" alt="Screenshot 2024-06-10 at 6 19 37 PM" src="https://github.com/swingerman/ha-dual-smart-thermostat/assets/293004/c59f2261-bc05-4b70-81ba-18db3be54597">

**Comment by swingerman** [comment]
Please try to omit those attributes too.

**Comment by mbrevda** [comment]
I don't have them set - is there another way to remove them?

```yaml
- platform: dual_smart_thermostat
  name: Boys Room
  heater: switch.boys_room_radiator
  cooler: switch.boys_room_air_conditioner
  target_sensor: sensor.boys_room_temperature_temperature
  min_cycle_duration: 60
  precision: .5
  min_temp: 20
  max_temp: 25
  away:
    temperature: 15
```
