### ISSUE TITLE
Issue: target_sensor_safety_delay is an invalid option

### ISSUE THREAD

**Issue by milandzuris** [swingerman/ha-dual-smart-thermostat#229]
target_sensor_safety_delay is an invalid option

```
  - platform: dual_smart_thermostat
    name: Bedroom Thermostat
    unique_id: Bedroom Thermostat
    heater: switch.bedroom_radiator
    cooler: fan.bedroom_fan
    target_sensor: sensor.bedroom_temperature
    sensor_stale_duration: 00:45:00
    openings:
      - binary_sensor.bedroom_window
      - binary_sensor.bedroom_second_window
    openings_scope:
      - heat
    min_temp: 18
    max_temp: 27
    target_temp: 23.0
    hot_tolerance: 0
    cold_tolerance: 0.20
    precision: 0.1
    target_temp_step: 0.5
    initial_hvac_mode: heat
```

Log:
```
Logger: homeassistant.config
Source: config.py:1294
First occurred: July 3, 2024 at 23:28:17 (12 occurrences)
Last logged: 00:03:29

Invalid config for 'climate' from integration 'dual_smart_thermostat' at climate.yaml, line 30: 'target_sensor_safety_delay' is an invalid option for 'dual_smart_thermostat.climate', check: target_sensor_safety_delay, please check the docs at https://github.com/swingerman/ha-dual-smart-thermostat.git
Invalid config for 'climate' from integration 'dual_smart_thermostat' at climate.yaml, line 51: 'target_sensor_safety_delay' is an invalid option for 'dual_smart_thermostat.climate', check: target_sensor_safety_delay, please check the docs at https://github.com/swingerman/ha-dual-smart-thermostat.git
Invalid config for 'climate' from integration 'dual_smart_thermostat' at climate.yaml, line 69: 'target_sensor_safety_delay' is an invalid option for 'dual_smart_thermostat.climate', check: target_sensor_safety_delay, please check the docs at https://github.com/swingerman/ha-dual-smart-thermostat.git
Invalid config for 'climate' from integration 'dual_smart_thermostat' at climate.yaml, line 90: 'target_sensor_safety_delay' is an invalid option for 'dual_smart_thermostat.climate', check: target_sensor_safety_delay, please check the docs at https://github.com/swingerman/ha-dual-smart-thermostat.git
Invalid config for 'climate' from integration 'dual_smart_thermostat' at climate.yaml, line 111: 'target_sensor_safety_delay' is an invalid option for 'dual_smart_thermostat.climate', check: target_sensor_safety_delay, please check the docs at https://github.com/swingerman/ha-dual-smart-thermostat.git
```
