### ISSUE TITLE
Restore state does not function with presets

### ISSUE THREAD

**Issue by gorstj** [swingerman/ha-dual-smart-thermostat#241]
Generally the dual-smart-thermostat is rock solid. I have almost finished two Blueprints that utilise it (one that uses a remote temperature sensor, as my AC gets hot air blown at it from my projector - genius! The other having zones for my ducted AC, each zone has. a virtual dual=smart-thermostat and the Blueprints controls a damper to switch on/off zones accordingly). I will link back from the Blueprint forum once I 'release'.

For one of my use cases I have two presets 'comfort' and 'away'
(I have an automation which switches between these depending if I am using the room)

The thermostat spendings most of it's time in 'away mode' (high:28 low:15)
![image](https://github.com/user-attachments/assets/8696aaee-8e37-4854-889c-affdbcd925a2)

If HA is restarted then it changes the temperature to whatever is stored in the 'none' preset (in this case high:24, low 15)
![image](https://github.com/user-attachments/assets/3dfec7e1-2453-436f-a6fc-5c3fa98932fd)

**The desired behaviour is that it remembers which exact setting it is immediately before restart, this may be a preset **

Here is my climate.yaml

```
- platform: dual_smart_thermostat
  name: Studio aircon
  heater: input_boolean.virtual_heater_studio # <-required
  cooler: input_boolean.virtual_cooler_studio # <-required
  fan: input_boolean.virtual_fan_studio
  target_sensor: sensor.studio_temp_humid_temperature
  heat_cool_mode: true # <-required
  cold_tolerance: 0.3
  hot_tolerance: 0.2
  fan_hot_tolerance: 1
  target_temp_step: 0.5
  min_temp: 14
  max_temp: 28
  comfort:
    temperature: 21
    target_temp_low: 21
    target_temp_high: 21.5
  away:
    temperature: 21
    target_temp_low: 15
    target_temp_high: 28
```

p.s. is there any way to have the thermostat run without the heater/cooler entity set? I have an automation which listens to change in state of the dual-thermostat instead - so these 'virtual' heater/cooler switches superfluous for me.
