### ISSUE TITLE
[bug] - hvac_action attribute never listed as 'fan'

### ISSUE THREAD

**Issue by gorstj** [swingerman/ha-dual-smart-thermostat#247]
I upgraded from 0.96 --> beta 4 --> 0.97 in recent days

Some time in that upgrade (without any other changes) the 'hvac_action' attribute no longer states 'fan' when it is within the fan_hot_tolerance range; instead it says cooling

The fan entity (in my case 'input_boolean.virtual_fan_studio') is still appropriately activated; see screenshot. It also activates the cooler entity at the appropriate time point.
![image](https://github.com/user-attachments/assets/e2ff47e6-fa02-4619-b752-d708fb8f824a)

Is this a deliberate change in behaviour? Or is this a bug?

The only reason it is relevant is my automation/blueprint is striggered off the hvac_action attribute to control the 'real' HVAC device. I can alter it to switch off the fan entity instead, but don't want to alter in unless I know it is a deliberate/permanent change.

```
- platform: dual_smart_thermostat
  name: Studio aircon
  heater: input_boolean.virtual_heater_studio # <-required
  cooler: input_boolean.virtual_cooler_studio # <-required
  fan: input_boolean.virtual_fan_studio
  target_sensor: sensor.studio_temp_humid_temperature
  heat_cool_mode: true # <-required
  cold_tolerance: 0.3
  hot_tolerance: 0.2
  fan_hot_tolerance: 1
  target_temp_step: 0.5
  min_temp: 14
  max_temp: 28
  comfort:
    temperature: 21
    target_temp_low: 21
    target_temp_high: 21.5
  away:
    temperature: 21
    target_temp_low: 15
    target_temp_high: 28
```
