### ISSUE TITLE
[bug] - hvac_action_reason empty after restart

### ISSUE THREAD

**Issue by swingerman** [swingerman/ha-dual-smart-thermostat#266]
I'm not sure if it is related (or helpful) but hvac_action_reason doesn't get set to anything at all after a restart until the thermostat takes some 'action' again.

So if it was target_temp_reached and you restart (or reload the YAML from Developer tools) then it remains as an empty attribute until something gets changed and causes an action to occur that would change it.

I've been trying to use it to determine if an AC has been turned off by the integration or manually from a control panel and the 'blank' value has caused some issues with the logic

_Originally posted by @cyberkryten in https://github.com/swingerman/ha-dual-smart-thermostat/issues/245#issuecomment-2262824221_

**Comment by swingerman** [comment]
@cyberkryten, @jacobw
Could you share your configuration please?

**Comment by jacobw** [comment]
```yaml
  - platform: dual_smart_thermostat
    name: Lounge Climate
    unique_id: lounge_climate
    heater: switch.lounge_heatpump_heat
    cooler: switch.lounge_heatpump_cool
    target_sensor: sensor.yz_666e_temperature
    sensor_stale_duration: 0:05
    heat_cool_mode: true
    min_temp: 15
    max_temp: 26
    target_temp: 21.5
    target_temp_high: 21.5
    target_temp_low: 19
    cold_tolerance: 0.5
    hot_tolerance: 0
    precision: 0.1
    target_temp_step: 0.5
```
