### ISSUE TITLE
[feat] - Proxy "Dumb" Climate entity

### ISSUE THREAD

**Issue by jack3308** [swingerman/ha-dual-smart-thermostat#281]
Add the option for the user to provide a climate entity already exposed in home assistant that dual-smart-thermostat should control instead of providing heating and/or cooling switches. This would be useful for bridging the gap left by so many crappy OEM integrations that don't provide pretty key components for a climate entity. Examples would be the Panasonic Comfort Cloud devices don't have temperature sensors exposed and so you don't have any idea what temperature the room is or if it's even heating or cooling to the set temperature. Additionally, this allows for easy addition of things like entry sensors, presets, and the like that have been half forgot by crappy OEM integrations.

**Comment by mbrevda** [comment]
I have a similar use case: I have a (fully functioning!) climate entity air conditioner, but I use it only for cooling, in addition to a switch entity used for heating. To use both in dual thermostat (DT), I've added the air conditioner as a switch template to HA, which I then use with DT. It would definitely be simpler if I could just assign the climate device directly to DT.

<details><summary>switch template</summary>

```yaml
- platform: template
  switches:
    kitchen_ac:
      value_template: "{{ is_state('climate.kitchen_air_conditioner', 'cool') }}"
      turn_on:
        - action: climate.set_temperature
          data:
            temperature: "{{ state_attr('climate.kitchen', 'temperature') }}" # <--- follow the DT climate entity
            hvac_mode: cool
          target:
            entity_id: climate.kitchen_air_conditioner
      turn_off:
        action: climate.turn_off
        target:
          entity_id: climate.kitchen_air_conditioner

```

</details> 

<details><summary>DT Climate entry</summary>

```yaml
- platform: dual_smart_thermostat
  name: Kitchen
  heater: switch.kitchen_radiator
  cooler: switch.kitchen_ac
  target_sensor: sensor.kitchen_thermostat_temperature
  min_cycle_duration: 60
  precision: .5
  min_temp: 18
  max_temp: 25
  away:
    temperature: 15
```
</details>

**Comment by cyberkryten** [comment]
At first, I found the switches annoying (the most annoying part is there's no "reload switches" option in HA, you have to do a restart).  However, the switches add a lot of flexibility to what you can do and how you manage the device and it also adds a layer of abstraction between this integration and those crappy ones!

This may not be entirely clear when you setup this integration, but it is very flexible and it means that if you can control the device in HA then you can setup Heat and Cool switches do control it by changing the state of the exposed climate.XXXXX entry.  Of course, it may be far simpler for those not used to coding to just link to the Climate Entity, but there are a lot of ways to control a Heater/AC/Heatpump etc, so I suspect doing so in a generic way will be quite difficult.


Here's a more complicated example of a switch used to control a Samsung AC unit via SmartThings.  I use multiple temp sensors because the AC temp doesn't give a representative actual room temperature, so the AC target gets set 5C below the actual target (to ensure the AC keeps running).  Also, the first 'command' to the AC unit doesn't always get actioned, so this method uses the initial set to 'auto' as a wake up for the Integration/SmartThings link.
It also allows me to set the fan speed to low overnight.

```

- platform: template
  switches:
    virtual_mainbed_cool:
      value_template: "{{is_state('climate.master_bedroom_ac', 'cool')}}"
      turn_on:
        - action: climate.set_fan_mode
          data:
            fan_mode: auto
          target:
            entity_id: climate.master_bedroom_ac
        - action: climate.set_temperature
          data:
            hvac_mode: cool
            temperature: "{{ (( state_attr('climate.mainbed_smart', 'temperature') if state_attr('climate.mainbed_smart', 'target_temp_high') == none else state_attr('climate.mainbed_smart', 'target_temp_high') ) - 5) | round(0, 'floor') }}"
          target:
            entity_id: climate.master_bedroom_ac
        - action: climate.set_fan_mode
          data:
            fan_mode: "{{ 'low' if ((now().hour < 8) or (state_attr('climate.mainbed_smart', 'preset_mode') == 'sleep')) else 'high' }}"
          target:
            entity_id: climate.master_bedroom_ac
      turn_off:
        - action: climate.turn_off
          target:
            entity_id: climate.master_bedroom_ac

```

**Comment by swingerman** [comment]
## Related: Examples Now Available

While native climate entity support isn't available yet, we've created comprehensive examples showing how to use switch templates and other workaround patterns effectively.

### Relevant Examples

**[Single-Mode Thermostat Wrapper](https://github.com/swingerman/ha-dual-smart-thermostat/tree/master/examples/single_mode_wrapper)** - Shows a complete pattern for wrapping a single-mode thermostat (similar to what @mbrevda and @cyberkryten describe):
- Uses input_boolean helpers as dummy switches
- Automation reconciles the dual thermostat to the real thermostat
- Achieves Nest-like "Keep Between" functionality
- Includes Apple Home integration examples

**[Basic Configurations](https://github.com/swingerman/ha-dual-smart-thermostat/tree/master/examples/basic_configurations)** - Various switch template patterns

**[Smart Scheduling](https://github.com/swingerman/ha-dual-smart-thermostat/tree/master/examples/integrations/smart_scheduling.yaml)** - Automation examples

### Your Use Cases

@mbrevda - Your switch template pattern for the air conditioner is perfect and could be added to the examples! It shows exactly how to bridge a climate entity to work with this integration.

@cyberkryten - Your sophisticated Samsung AC switch with multiple temperature sensors and conditional fan modes is an excellent advanced example of what's possible with switch templates.

### Future Native Support

These examples demonstrate that while native climate entity control would be more convenient, the current switch-based approach is actually quite powerful and flexible. If/when native support is added (issue #281), these patterns will still be useful for understanding the underlying concepts.

Would either of you be willing to contribute your switch templates to the examples directory? They'd be valuable for the community!

Related: Issue #432

**Comment by mbrevda** [comment]
Feel free to use it.

Thinking of how many lines of text are needed to explain how this all works. On top of the user's time to trt and parse it, get it set up, test/debug, etc. Feels like just doing it right would be a lot easier

**Comment by cyberkryten** [comment]
Apologies, I'd been away and then forgot to reply.  

My setup is built on other examples, so it's just changes and refinement - every install is different which is why HA is great and this thermostat replaced a ton of (very buggy) scripts, automations and templates!

After a summer of tweaking AC and with the onset of winter my templates have got more involved as I found the time to reevaluate the dual-stage heating.  

As a result I now have three switches per zone:

1.  the primary heating setup (using the gas boiler which drives the wet underfloor heating loops)
2. AC Cooling
3. AC Heating as a secondary heater

@mbrevda I don't like the fact there's so many repeated lines within these templates, but I've found it is all necessary - this is worse when you consider that I have seven separate zones, for which this is repeated almost identically for each (though without the nighttime overrides the bedrooms use).  

That's not the fault of the integration, just a problem I find I have throughout HA - code instantiation, inheritance and re-use doesn't exist so you are forced to duplicate everything.  If anyone has any suggestions to tidy things up it would be great (eg even something as simple as setting a variable to store HEATER and AC instead of having to use climate.<namehere> repeatedly would make the job of others copy+pasting these easier - it would also stop me accidentally turning on the bedroom AC unit when the Office needs heat (I wasted a day on that one!!)

There's a trick in the secondary heating stuff to deal with things I couldn't do with the standard secondary config to not turn it on overnight (as it annoys people) - it does seem to confuse the Smart Thermostat status display at times, but it works fine.

The flexibility to call switches gives you options, whilst being able to target a climate.xxx entity directly is simpler, it just wouldn't work for my setup as the AC unit thermostats are not accurate (when the AC isn't running), so it's great that this will be kept available - I'm sure it's not ideal for newbies or those wanting to config via the UI, but it's great to have the choice.

Also worth noting that the latest version of HA does reload the switch entities when you reload YAML for Templates from the Dev Tools which has made making changes far easier than having to do a full restart every time.  I have found that reloading those and the dual_smart_thermostat can cause some oddities, so usually manually do a 'temp up/ temp down' on each Smart Thermostat after the reloads to force a recalculation of states (if I ever pin down what happens with debug I'll raise it).



```
#Main Bedroom
- platform: template
  switches:
    virtual_mainbed_cool:
      value_template: "{{is_state('climate.master_bedroom_ac', 'cool')}}"
      turn_on:
        - action: climate.set_fan_mode
          data:
            fan_mode: auto
          target:
            entity_id: climate.master_bedroom_ac
        - action: climate.set_temperature
          data:
            hvac_mode: cool
            temperature: "{{ (( state_attr('climate.mainbed_smart', 'temperature') if state_attr('climate.mainbed_smart', 'target_temp_high') == none else state_attr('climate.mainbed_smart', 'target_temp_high') ) - 5) | round(0, 'floor') }}"
          target:
            entity_id: climate.master_bedroom_ac
        - action: climate.set_fan_mode
          data:
            fan_mode: "{{ 'low' if ((now().hour < 8) or (state_attr('climate.mainbed_smart', 'preset_mode') == 'sleep')) else 'high' }}"
          target:
            entity_id: climate.master_bedroom_ac
      turn_off:
        - action: climate.turn_off
          target:
            entity_id: climate.master_bedroom_ac

    virtual_mainbed_heat:
      value_template: "{{is_state('climate.mainbed', 'heat')}}"
      turn_on:
        - action: climate.set_preset_mode
          target:
            entity_id: climate.mainbed
          data:
            preset_mode: High
        - action: climate.set_temperature
          data:
            temperature: "{{ (( state_attr('climate.mainbed_smart', 'temperature') if state_attr('climate.mainbed_smart', 'target_temp_low') == none else state_attr('climate.mainbed_smart', 'target_temp_low') ) + 3) | round(0, 'ceiling') }}"
          target:
            entity_id: climate.mainbed
      turn_off:
        - action: climate.set_preset_mode
          target:
            entity_id: climate.mainbed
          data:
            preset_mode: Low
        - action: climate.set_temperature
          data:
            temperature: "{{ (( state_attr('climate.mainbed_smart', 'temperature') if state_attr('climate.mainbed_smart', 'target_temp_low') == none else state_attr('climate.mainbed_smart', 'target_temp_low') ) - 5) | round(0, 'floor') }}"
          target:
            entity_id: climate.mainbed

    virtual_mainbed_heat_ac:
      value_template: "{{is_state('climate.master_bedroom_ac', 'heat')}}"
      turn_on:
        - action: climate.set_fan_mode
          data:
            fan_mode: auto
          target:
            entity_id: climate.master_bedroom_ac
        - action: climate.set_temperature
          data:
            hvac_mode: "{{ 'off' if ((now().hour < 8) or (now().hour >= 22) or (state_attr('climate.mainbed_smart', 'preset_mode') == 'sleep')) else 'heat' }}"
            temperature: "{{ (( state_attr('climate.mainbed_smart', 'temperature') if state_attr('climate.mainbed_smart', 'target_temp_low') == none else state_attr('climate.mainbed_smart', 'target_temp_low') ) + 3) | round(0, 'ceiling') }}"
          target:
            entity_id: climate.master_bedroom_ac
        - action: climate.set_fan_mode
          data:
            fan_mode: "{{ 'low' if ((now().hour < 8) or (state_attr('climate.mainbed_smart', 'preset_mode') == 'sleep')) else 'high' }}"
          target:
            entity_id: climate.master_bedroom_ac
      turn_off:
        - action: climate.turn_off
          target:
            entity_id: climate.master_bedroom_ac
```
