### ISSUE TITLE
Troubleshooting heat pump cooling 

### ISSUE THREAD

**Issue by dgoodwin430** [swingerman/ha-dual-smart-thermostat#288]
I have not been able to get the heat pump cooling portion to work. I have a 2 stage heat pump with a switching valve. If I remove the heat pump cooling portion everything works as it should but of course I have to control the valve manually. 

```python
  - platform: dual_smart_thermostat
    name: HeatPump1
    heater: input_boolean.heatpump1heat
    #cooler: input_boolean.heatpump1cool
    #heat_cool_reverse_entity: switch.heatpump1valve
    secondary_heater: switch.heatpump1stage2
    secondary_heater_timeout: 00:00:30
    secondary_heater_dual_mode: true
    target_sensor: sensor.climate_average_1
    heat_pump_cooling: input_boolean.heatpump1cool
    min_temp: 40
    max_temp: 90
    heat_cool_mode: true # <-required
    #ac_mode: true
    initial_hvac_mode: "heat_cool"
    target_temp: 70
    target_temp_low: 65
    target_temp_high: 75
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    precision: 1.0
```

**Comment by swingerman** [comment]
The reverse entity is called `heat_pump_cooling`, have you tried that?

**Comment by swingerman** [comment]
Could you please elaborate on what exactly is not happening when the cooling is enabled?

**Comment by dgoodwin430** [comment]
Does the yaml configuration at least look correct for this application?

**Comment by bassdr** [comment]
Something here, I tried many configurations, and even trying to keep it to a minimum "heating", "cooling" and "target_sensor" does not work... It stays idle no matter what temperature I set. Heat or cool...

```
hvac_modes:
  - heat_cool
  - heat
  - cool
  - "off"
min_temp: 7
max_temp: 35
target_temp_step: 0.5
current_temperature: 25.8
temperature: 21
hvac_action: idle
prev_target_temp_low: 21.5
prev_target_temp_high: 23.5
hvac_action_reason: target_temp_not_reached
friendly_name: HVAC Controller
supported_features: 385
```

**Comment by bassdr** [comment]
Nevermind, I had a dumb typo in my configuration.yaml, it works now and I believe I have the same setup as you, so here's a solution (workaround?): setup two input_boolean. Mine are called "hvac_heater" and "hvac_cooler" and add a small automation that drives the actual "y", "o/b" and "g" wires. I could not find another way using the hacs, or it's not documented...

```yaml
alias: HVAC Standard Interface
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.hvac_heater
      - input_boolean.hvac_cooler
      - input_boolean.hvac_fan
    id: controlled
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.hvac_heater
            state: "on"
        sequence:
          - action: switch.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: switch.hvac_y
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.hvac_ob
      - conditions:
          - condition: state
            entity_id: input_boolean.hvac_cooler
            state: "on"
        sequence:
          - action: switch.turn_on
            metadata: {}
            data: {}
            target:
              entity_id:
                - switch.hvac_y
                - switch.hvac_ob
      - conditions:
          - condition: state
            entity_id: input_boolean.hvac_fan
            state: "on"
        sequence:
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.hvac_y
          - action: switch.turn_on
            target:
              entity_id: switch.hvac_ob
            data: {}
    default:
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
            - switch.hvac_y
            - switch.hvac_ob
mode: queued
max: 10
```
