### ISSUE TITLE
[bug] - temperature null when changing hvac mode

### ISSUE THREAD

**Issue by mikelauritsen** [swingerman/ha-dual-smart-thermostat#289]
After upgrading from v0.9.7 to 0.9.8 the temperature is set to 'null' (shown as attribute) when changing hvac mode. 
When this happens I have to manually set the temperature attribute via developer tool to be able to control the temperature.
Downgraded to v.0.9.7 and the temperature is persistent when changing hvac mode.

```
climate:
  - platform: dual_smart_thermostat
    unique_id: dual_smart_thermostat.hvac
    name: HVAC
    heater: input_boolean.hvac_heat
    cooler: input_boolean.hvac_cool
    target_sensor: sensor.temperature
    min_temp: 16
    max_temp: 30
    ac_mode: false
    cold_tolerance: 1
    hot_tolerance: 1
    precision: 0.1
    target_temp_step: 1.0
```
![image](https://github.com/user-attachments/assets/0a094dfc-e313-48ca-95dc-3e446f378abb)
![image](https://github.com/user-attachments/assets/52d3b75b-fcfd-4ea6-84a8-bb0e5bf67565)
![image](https://github.com/user-attachments/assets/bd06afbd-5a7d-442f-a4f7-cd31f3e7f839)
