### ISSUE TITLE
climate.set_temperature only works if both values are set

### ISSUE THREAD

**Issue by bkbartk** [swingerman/ha-dual-smart-thermostat#293]
I want to run an automation to automatically set the target_temp_low
```
data:
  target_temp_low: 18
target:
  entity_id: climate.thermostaat_woonkamer_voor
action: climate.set_temperature

```
but this always fails if I don't add the `target_temp_high` as well. I my case this is not ideal,
Is there a way work around this?
