### ISSUE TITLE
[bug] - Thermostats wrongly remain in TARGET_TEMPERATURE_RANGE mode

### ISSUE THREAD

**Issue by mat1990dj** [swingerman/ha-dual-smart-thermostat#299]
I have a thermostat that was previously defined as heat_cool_mode: true with a target_temp_high and target_temp_low.
I no longer want to use that thermostat in heat_cool_mode so I replaced the two target temperatures by a single target temperature, and changed heat_cool_mode to false.
The thermostat still has a prev_target_temp_low and prev_target_temp_high and is still anounced as supported_features: 40**2** which makes it have a target_temp_high and target_temp_low temps.
I would like the thermostat to be reported as a supported_features: 40**1** and the min/max target temperatures to be removed as I no longer want to use this thermostat in this mode.

Config:
```
  - platform: dual_smart_thermostat
    name: Kitchen
    unique_id: kitchen
    heater: input_boolean.heat_request_kitchen
    cooler: input_boolean.cool_request_kitchen
    target_sensor: sensor.kitchen_temperature
    humidity_sensor: sensor.kitchen_humidity
    heat_cool_mode: false
    target_temp: 75
    initial_hvac_mode: "off"
    min_temp: 60
    max_temp: 85
    precision: 1
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    min_cycle_duration:
      seconds: 30
    keep_alive:
      minutes: 1
    eco:
        #En esa habitacion ECO
        temperature: 68
        #temperature: 80
    home:
        #No en esa habitacion
        temperature: 66
        #temperature: 82
    comfort:
        #Normal caliente/frio
        temperature: 70
        #temperature: 78
    away:
        #Fuera de casa menos de 24h
        temperature: 60
        #temperature: 85
    anti_freeze:
        #Fuera de casa por períodos largos
        temperature: 40
        #temperature: 95
```

reported states:
![image](https://github.com/user-attachments/assets/e6487440-5f18-4c40-a8f6-fa0ac3f3df40)
