### ISSUE TITLE
[feat] - Thermostat Off

### ISSUE THREAD

**Issue by milandzuris** [swingerman/ha-dual-smart-thermostat#303]
Hi, i have some problem when thermostat is Off and radiator is manually turned On and the temperature will change (update) thermostat turn Off my radiator but i dont want for the thermostat to control it, can you remake it or add some function so that it can be turned off?.

**Comment by milandzuris** [comment]
@swingerman Hi something new?

**Comment by swingerman** [comment]
Fixed the issue. I will include it in the next release

**Comment by milandzuris** [comment]
> Fixed the issue. I will include it in the next release

is it possible to release it now as Beta?

**Comment by swingerman** [comment]
Here you go: [v0.9.10-beta-1](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.10-beta-1)

**Comment by milandzuris** [comment]
> Here you go: [v0.9.10-beta-1](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.10-beta-1)

thank you very much

**Comment by milandzuris** [comment]
I have a question and is it necessary to add something else to the config?, because this function doesn't work anyway. @swingerman

**Comment by swingerman** [comment]
Could you post your config and steps to reproduce the issue?

**Comment by milandzuris** [comment]
> Could you post your config and steps to reproduce the issue?

```
#Bedroom Thermostat
  - platform: dual_smart_thermostat
    name: Bedroom Thermostat
    unique_id: Bedroom Thermostat
    heater: switch.bedroom_radiator
    cooler: fan.bedroom_fan
    target_sensor: sensor.bedroom_temperature
    sensor_stale_duration: 00:45:00
    openings:
      - binary_sensor.bedroom_window
      - binary_sensor.bedroom_second_window
    openings_scope:
      - heat
    min_temp: 18
    max_temp: 27
    target_temp: 23.0
    hot_tolerance: 0
    cold_tolerance: 0.20
    precision: 0.1
    target_temp_step: 0.5
    initial_hvac_mode: heat
```
