### ISSUE TITLE
[bug] - thermostat turn off after restart HA in some conditions

### ISSUE THREAD

**Issue by Anry777** [swingerman/ha-dual-smart-thermostat#307]
Thermostat turn off after restart HA:
1. It in dualmode (heater and cooler are selected in config)
2. Some preset selected (not "None")

If selected heater only  - it recover previous state after reboot with any preset selected .

before restart  
![image](https://github.com/user-attachments/assets/eeaedbbe-31df-4011-96bb-9203c09848f2)
after restart
![image](https://github.com/user-attachments/assets/7dffabd0-4948-42ed-b8a6-83e7356e0fa8)

First thermostat 
```yaml
- platform: dual_smart_thermostat
  unique_id: thermostat_gostinnaya
  name: Гостинная
  heater: switch.heater_gostinnaya
  cooler: switch.ac_gostinnaya_cool
  target_sensor: sensor.temp_gostinnaya_temperature
  min_temp: 15
  max_temp: 28
  target_temp: 24
  target_temp_high: 26.5
  target_temp_low: 24
  cold_tolerance: 0.3
  hot_tolerance: 0.3
  min_cycle_duration:
    seconds: 5
  away: # this preset will be available for all hvac modes
    temperature: 18
  home: # this preset will be available only for heat or cool hvac mode
    temperature: 24
  precision: 0.1
  target_temp_step: 0.5
  keep_alive:
    minutes: 3
```

Second thermostat
```yaml
- platform: dual_smart_thermostat
  unique_id: thermostat_vannaya
  name: Ванная
  heater: switch.otoplenie_relay_board_vannaya
  target_sensor: sensor.temp_vannaya_temperature
  min_temp: 15
  max_temp: 28
  target_temp: 25
  hot_tolerance: 0.3
  min_cycle_duration:
    minutes: 3
  away: # this preset will be available for all hvac modes
    temperature: 18
  home: # this preset will be available only for heat or cool hvac mode
    temperature: 25
  precision: 0.1
  target_temp_step: 0.5
  keep_alive:
    minutes: 3`
```

**Comment by swingerman** [comment]
As I can see the preset get's see to none for some reason

**Comment by serlinGi** [comment]
Hi,
I don't undestand if my conf it's wrong but at restart is all off without preset

this is my conf
```climate:
  - platform: dual_smart_thermostat
    name: "climatizzatore cucina"
    unique_id: climate.climatizzatore_cucina
    heater: switch.clima_cucina
    heat_pump_cooling: sensor.fancoil_mode
    target_sensor: sensor.aqara_cucina_temperature
    heat_cool_mode: true
    openings:
      - entity_id: binary_sensor.terrazzo_cucina_contact
        timeout: 00:03:00
    keep_alive: #lo attivo e commento initial_hvac_mode per verificare se mantiene lo stato al riavvio
      minutes: 1
    min_temp: 15
    max_temp: 28
    precision: 0.5
    cold_tolerance: 0.4
    hot_tolerance: 0.1
    target_temp_step: 0.1
    min_cycle_duration:
      minutes: 1
    away:
      temperature: 18.0
    home:
      temperature: 23.5
    comfort:
      temperature: 22.5
    sleep:
      temperature: 19.0
  #
```
and I attach 2 shot with the states before and after reboot.

can You take a look at what I did wrong? 
(don't consider "studio", there I acted manually before the screenshot😬)

thx
![Screenshot_2024-12-07-13-30-51-18_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/a835330e-d99b-448f-b7ba-19ce30535000)
before reboot 👆

![Screenshot_2024-12-07-13-21-45-57_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/8c6f4c92-1e9b-4bf9-9a3a-232a22566870)
after reboot 👆

P.S.
HA.OS 13.2
core 2024.12.1
dual smart 0.9.9

**Comment by mat1990dj** [comment]
Same here with 0.9.9

**Comment by serlinGi** [comment]
Hi,
I had to restart HA when only one of my thermostats was active and I think I found a possible cause;
he was the only one to find himself with the preset mode in "none".
the only 1 error in log is:
```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:608
integration: Climate (documentation, issues)
First occurred: 23:08:44 (1 occurrences)
Last logged: 23:08:44

Error adding entity climate.climatizzatore_letto for domain climate with platform dual_smart_thermostat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 608, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 927, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1383, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/dual_smart_thermostat/climate.py", line 618, in async_added_to_hass
    self.presets.apply_old_state(old_state)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/config/custom_components/dual_smart_thermostat/managers/preset_manager.py", line 198, in apply_old_state
    else float(preset.to_dict.get(ATTR_TARGET_TEMP_LOW))
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
```
and immediately after this warning too:
```
This error originated from a custom integration.

Logger: custom_components.dual_smart_thermostat.hvac_device.heat_pump_device
Source: custom_components/dual_smart_thermostat/hvac_device/heat_pump_device.py:175
integration: dual_smart_thermostat (documentation, issues)
First occurred: 23:08:44 (7 occurrences)
Last logged: 23:08:44

Heat pump cooling entity state is unknown or unavailable: <state sensor.fancoil_mode=unknown; friendly_name=fancoil mode @ 2024-12-10T23:08:34.504027+01:00>
```
which refers to the sensor being powered to assume the value "heating" or "cooling" for the heat_pump_cooling in conf , based on the state of an input.select helper

questo il sensore:
```
sensor:
  - platform: template
    sensors:
      fancoil_mode:
        friendly_name: "fancoil mode"
        unique_id: "fancoil mode"
        value_template: >
           {{ states('input_select.caldo_freddo_mod') }}  
```

and this the helper:

```
input_select:
  caldo_freddo_mod:
    name: "mod. caldo-freddo"
    options: 
      - heating
      - cooling
#

```

well, maybe it can be related to the reboot times and the fact that the sensor is not ready yet?

or did I do something wrong in the way I set everything up, since my thermostat is controlled by just one switch for both modes?

thx :)
