### ISSUE TITLE
Max floor temperature setting ignored

### ISSUE THREAD

**Issue by bence056** [swingerman/ha-dual-smart-thermostat#315]
I have my in-floor heating set up with a floor sensor. No matter what I set for the max_floor_temp config entry, the floor temperature never goes above 28.5ish °C. and the system turns idle when the floor reaches 28°C.  (I assume the default value) I think my config is correct, but I will paste it in just in case.

```
climate:
  - platform: dual_smart_thermostat
    name: Hallway Floor Thermostat
    heater: switch.shelly1pmg3_543204592dfc_switch_0
    target_sensor: sensor.sbht_003c_3e98_temperature
    initial_hvac_mode: "heat"
    floor_sensor: sensor.shelly1pmg3_543204592dfc_temperature # <-required
    max_floor_temp: 32 # <-required
```
