### ISSUE TITLE
Attributes target_temp_high and target_temp_low are not always set

### ISSUE THREAD

**Issue by cyberkryten** [swingerman/ha-dual-smart-thermostat#324]
I've been trying to figure out why my temperature updates of the target thermostats keep failing and have finally figured out that the attributes I am reading the set Dual Smart temperature from are vanishing at times.

I am using switches to do this which setup the Underfloor heating thermostat for heating modes and AC system for cooling modes.  Here's the code in use for the Office switches to control the actual devices.:

```
- platform: template
  switches:
    virtual_office_cool:
      value_template: "{{is_state('climate.office_ac', 'cool')}}"
      turn_on:
        - action: climate.set_fan_mode
          data:
            fan_mode: auto
          target:
            entity_id: climate.office_ac
        - action: climate.set_temperature
          data:
            hvac_mode: cool
            temperature: "{{ (state_attr('climate.office_smart', 'target_temp_high') - 3) | round(0, 'floor') }}"
          target:
            entity_id: climate.office_ac
        - action: climate.set_fan_mode
          data:
            fan_mode: high
          target:
            entity_id: climate.office_ac
      turn_off:
        - action: climate.turn_off
          target:
            entity_id: climate.office_ac

    virtual_office_heat:
      value_template: "{{is_state('climate.office', 'heat')}}"
      turn_on:
        - action: climate.set_preset_mode
          target:
            entity_id: climate.office
          data:
            preset_mode: High
        - action: climate.set_temperature
          data:
            temperature: "{{ (state_attr('climate.office_smart', 'target_temp_low') + 3) | round(0, 'ceiling') }}"
          target:
            entity_id: climate.office

      turn_off:
        - action: climate.set_preset_mode
          target:
            entity_id: climate.office
          data:
            preset_mode: Low
        - action: climate.set_temperature
          data:
            temperature: "{{ (state_attr('climate.office_smart', 'target_temp_low') - 5) | round(0, 'floor') }}"
          target:
            entity_id: climate.office
```

Usually, I can read the set values from the documented attributes which are these:

```
target_temp_high: 26
target_temp_low: 22
```

However, at times, these two attributes stop getting set and seem to be replaced with versions prefixed with 'prev_' 

Here's the current state of attributes for my climate.office_smart thermostat, taken from the Developer Tools States tab:

```
hvac_modes: heat_cool, heat, cool, off
min_temp: 12
max_temp: 30
target_temp_step: 1
preset_modes: away, none
current_temperature: 24
temperature: 26
hvac_action: idle
preset_mode: none
prev_target_temp_low: 22
prev_target_temp_high: 28
hvac_action_reason: 
friendly_name: Office Smart
supported_features: 401
```

As you can see, the documented attributes are missing and have been replaced by versions with prev_ on the front - this causes exceptions within the actions because the state_attr call fails to return a value for the current high/low target temperature.

These prev_ versions are not documented.

Sometimes, both are present:

```
hvac_modes: heat_cool, heat, cool, off
min_temp: 12
max_temp: 30
target_temp_step: 1
preset_modes: away, none
current_temperature: 24
target_temp_high: 28
target_temp_low: 26
hvac_action: heating
preset_mode: none
prev_target_temp_low: 26
prev_target_temp_high: 28
hvac_action_reason: 
friendly_name: Office Smart
supported_features: 402
```
