### ISSUE TITLE
[bug] - Unable to set `hvac_mode` from automation

### ISSUE THREAD

**Issue by brodyhoskins** [swingerman/ha-dual-smart-thermostat#338]
I have a thermostat configured as follows:

```yaml
climate:
  - platform: dual_smart_thermostat
    name: Office Thermostat
    heater: switch.shelly1pm_3494547839ca
    target_sensor: sensor.office_sensor_temperature_3
    initial_hvac_mode: "off"
    min_temp: 60
    max_temp: 80
```

I have an automation that I would have set the `hvac_mode` to "heat", so it's configured like:

```yaml
action: climate.set_temperature
data:
  temperature: 72
  hvac_mode: heat
target:
  entity_id: climate.office_thermostat
```

The issue is that while the target temperature is set, the `hvac_mode` does not switch from "off" to "heat."
