### ISSUE TITLE
heat_pump_cooling switch is not activating cooling mode

### ISSUE THREAD

**Issue by nzrunner** [swingerman/ha-dual-smart-thermostat#370]
Gidday

I have followed the instructions to use a single switch for both heating and cooling, but it never activates cooling mode. My configuration is as follows: -

### Versions
- Home Assistant: 2025.3..4
- Dual Smart Thermostat: v0.9.10

### Dashboard Card
![Image](https://github.com/user-attachments/assets/7116d36c-ab67-4849-b566-cc305a2a966c)

### Developer Tools
![Image](https://github.com/user-attachments/assets/8768160c-a5bb-403a-9be8-17511e60a169)

### configuration.yaml
```
- platform: dual_smart_thermostat
  unique_id: d7a318de-02d1-4f88-b94a-52eff321c23e
  name: Bedroom Climate Controller
  heater: switch.plug_2_switch_1
  target_sensor: sensor.bedroom_temperature
  heat_pump_cooling: sensor.bedroom_climate_mode
  heat_cool_mode: true
  initial_hvac_mode: "heat_cool"
  min_temp: 5
  max_temp: 40
  ac_mode: false
  target_temp: 22
  target_temp_low: 21.5
  target_temp_high: 22.5
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  precision: 0.1
  target_temp_step: 0.1
  min_cycle_duration:
    seconds: 30
```
As you can see, my heat_pump_cooling sensor is set to 'cooling' but the dual_smart_thermostat has HVAC modes of 'heat, heat_cool, off'.

I have restarted Home Assistant several times to make sure any changes I made to the configuration were correctly applied.

Any thoughts on what I may have done wrong?
