### ISSUE TITLE
Fan not working

### ISSUE THREAD

**Issue by sembeek** [swingerman/ha-dual-smart-thermostat#374]
Hi,

Thank you for your work, everything works great, except for the fan part.
I have the following config:

```
climate:
  - platform: dual_smart_thermostat
    heater: switch.esphome_thermostat_force_heat
    target_sensor: sensor.smoothed_thermostat_temperature
    heat_pump_cooling: input_boolean.ecodan_heatpump_is_cooling
    humidity_sensor: sensor.humidity_2
    cold_tolerance: 1
    hot_tolerance: 1
    precision: 0.1
    target_temp_step: 0.1
    fan_hot_tolerance: 0.5
    fan: switch.fan_control
    fan_air_outside: true
    fan_hot_tolerance_toggle: input_boolean.hvac_fan
    outside_sensor: sensor.average_temperature_outside
```

My expectation is that when the inside temp is 21.9 and the thermostat is set to 21.7 (and outside temp is 19.5) it should turn on the fan, but it doesn't.
Am i doing something wrong, there is nothing in the logs.
These are the attributes of the thermostat:
```
hvac_modes: off, cool
min_temp: 7
max_temp: 35
target_temp_step: 0.1
current_temperature: 21.9
temperature: 21.7
hvac_action: idle
hvac_action_reason: 
friendly_name: Dual Smart Thermostat
supported_features: 385
current_humidity: 50.595
prev_target_temp: 21.6
```
