### ISSUE TITLE
Gym mode - cool to temp, when reached change to fan only

### ISSUE THREAD

**Issue by cyberkryten** [swingerman/ha-dual-smart-thermostat#380]
I'm struggling to get the AC unit in our home gym to do what my wife wants - it is a Samsung on-wall unit and there is no other heating in the room so it is normally set with min/max temps in Dual Smart with a wide range and it keeps within that range absolutely fine.

Effectively, she wants it to cool the room down and then continue to run airflow all the time, cold air to cool and then after just recirculating as she likes the breeze.

I've tried several options, but what I can't seem to do is figure out how to get it to change from Cool mode into Fan Only once the target temperature is reached.  If I use the AC's Auto mode, it turns off once temp is reached.  The normal Dual Smart setup also turns off once the target temp is reached.

The only way I can seem to do it is set the AC temp to the absolute minimum of 12C but then it is too cold.

I've had a play with the 'fan' modes but they all seem to relate to systems which need separate control of fans when heat/cooling and not an actual fan only use of an AC unit.

Anyone done this with other automations, if not, is this something this integration could add, a "Gym mode" or even a switch on the "Activity" mode to add 'Fan only when below set temp"?

**Comment by swingerman** [comment]
How do you control that AC? Theoretically, Dual Smart has a fan mode tolerance feature, but that requires you to be able to send the fan mode command to the AC

**Comment by cyberkryten** [comment]
Apologies, I missed your question.

The AC unit is a normal wall mounted (Samsung) unit that I control using the SmartThings integration.  It doesn't seem to fit with the "Fan mode" definitions in the integration as most of those seem geared to 'central' AC systems where the AC and fan are controlled separately.

The unit can be put into "Fan only" mode to just blow air, but I can't find a way for the DualSmart to transition to that once the set temp is reached - it always seems to turn the AC unit off.

It is almost the opposite of fan_on_with_ac that I wan't - basically a mode where if the AC is not on then turn on the fan!

I do have switches setup, so I guess I could try putting some logic into that so that if "gym mode' is enabled it doesn't turn off, but instead changes to fan only.

This is the Dual Smart config:

```
- platform: dual_smart_thermostat
  name: Garage Smart
  unique_id: garage_smart
  heater: switch.virtual_garage_heat
  cooler: switch.virtual_garage_cool
  target_sensor: sensor.virtual_garage_temperature
  heat_cool_mode: true # <-required
  cold_tolerance: 0.2
  hot_tolerance: 0.2
  precision: 0.1
  target_temp_step: 1
  min_temp: 12
  max_temp: 30
  target_temp_low: 15
  target_temp_high: 25
  min_cycle_duration:
    minutes: 5
  away:
    target_temp_low: 12
    target_temp_high: 29
  activity:
    target_temp_low: 18
    target_temp_high: 20
  home:
    target_temp_low: 15
    target_temp_high: 27
```


Here's the switch that is used for the cooling:

```
- platform: template
  switches:
    virtual_garage_cool:
      value_template: "{{is_state('climate.garage_ac', 'cool')}}"
      turn_on:
        - action: climate.turn_on
          target:
            entity_id: climate.garage_ac
        - action: climate.set_fan_mode
          data:
            fan_mode: auto
          target:
            entity_id: climate.garage_ac
        - action: climate.set_temperature
          data:
            hvac_mode: cool
            temperature: "{{ (( state_attr('climate.garage_smart', 'temperature') if state_attr('climate.garage_smart', 'target_temp_high') == none else state_attr('climate.garage_smart', 'target_temp_high') ) - 5) | round(0, 'floor') }}"
          target:
            entity_id: climate.garage_ac
        - action: climate.set_fan_mode
          data:
            fan_mode: high
          target:
            entity_id: climate.garage_ac
        - action: climate.set_swing_mode
          data:
            swing_mode: vertical
          target:
            entity_id: climate.garage_ac
      turn_off:
        - action: climate.turn_off
          target:
            entity_id: climate.garage_ac
```
