### ISSUE TITLE
Changed setpoints not saving after restart

### ISSUE THREAD

**Issue by Lzryde** [swingerman/ha-dual-smart-thermostat#381]
I have this thermostat set up and working fine, but I think because it is added to home assistant through the configuration.yaml it does not have a unique id and the thermostat settings are not saved when my home assistant server does its nightly restart because the thermostat is recreated from the configuration.yaml every restart.
At least I think that's how this works?

I think this also causes issues with adding cards to to the dashboard.
I can't get mushroom climate cards to work, upon adding the card it says "o is not iterable"

I'm fairly new to home assistant so I'm probably doing something wrong or my expectations are wrong.

Here's my configuration.yaml for reference.

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#
#

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

climate:
  - platform: dual_smart_thermostat
    name: activityrm
    heater: switch.activity_room_heating
    cooler: switch.activity_room_cooling
    target_sensor: sensor.outdoor_meter_03_temperature
    heat_cool_mode: true # <-required
    initial_hvac_mode: "heat_cool"
    min_temp: 62
    max_temp: 86
    ac_mode: false
    target_temp: 70
    target_temp_high: 72
    target_temp_low: 67
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      minutes: 5
    keep_alive:
      minutes: 3
    away: # this preset will be available for all hvac modes
      temperature: 65
      target_temp_low: 62
      target_temp_high: 75
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 70
    precision: 0.1
    target_temp_step: 1

  - platform: dual_smart_thermostat
    name: livingrm
    heater: switch.living_room_heating
    cooler: switch.living_room_cooling
    target_sensor: sensor.outdoor_meter_02_temperature
    heat_cool_mode: true # <-required
    initial_hvac_mode: "heat_cool"
    min_temp: 62
    max_temp: 86
    ac_mode: false
    target_temp: 70
    target_temp_high: 72
    target_temp_low: 67
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      minutes: 5
    keep_alive:
      minutes: 3
    away: # this preset will be available for all hvac modes
      temperature: 65
      target_temp_low: 62
      target_temp_high: 75
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 70
    precision: 0.1
    target_temp_step: 1

  - platform: dual_smart_thermostat
    name: bedroomrm
    heater: switch.bedroom_room_heating
    cooler: switch.bedroom_room_cooling
    target_sensor: sensor.outdoor_meter_01_temperature
    heat_cool_mode: true # <-required
    initial_hvac_mode: "heat_cool"
    min_temp: 62
    max_temp: 86
    ac_mode: false
    target_temp: 70
    target_temp_high: 72
    target_temp_low: 67
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      minutes: 5
    keep_alive:
      minutes: 3
    away: # this preset will be available for all hvac modes
      temperature: 65
      target_temp_low: 62
      target_temp_high: 75
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 70
    precision: 0.1
    target_temp_step: 1

```
