### ISSUE TITLE
heat_pump_cooling usage with helper entity

### ISSUE THREAD

**Issue by cputoaster** [swingerman/ha-dual-smart-thermostat#384]
I use a helper binary_sensor to calculate the heat_pump_cooling value from some temperature value of the heat pump. Somehow, on a restart of home assistant, all thermostats are switched to "off". I can then go to the UI and set all of them from "off" to "Cool" or "HEAT" manually, but it's not convenient.

Could this be because the helper sensor is "unknown" in the beginning of startup? What would be a good way to fix it? As soon as there is a value of the helper entitiy, it would be great if the thermostat would start (heat or cool) the valves again.

**Comment by swingerman** [comment]
Could you please share your YAML config? Usually, after a restart, the thermostat should start in the last used HVAC mode. However, if you set the initial_hvac_mode in your configuration, the thermostat will use that setting.

**Comment by cputoaster** [comment]
Thank you very much for your input, I only got around to this now:

Config for the helper:

<img width="601" alt="Image" src="https://github.com/user-attachments/assets/875676bb-944b-4300-a653-f7fa632a1c90" />


config for thermostat:

```
climate:
  - platform: dual_smart_thermostat
    name: Parents Bedroom Thermostat
    heater: switch.parents_bedroom_heating_valve
    target_sensor: sensor.parents_bedroom_thermometer_temperature
    heat_pump_cooling: binary_sensor.cooling_mode
```

**Comment by swingerman** [comment]
Try this config (adding **unique_id**):

```yaml
climate:
  - platform: dual_smart_thermostat
    name: Parents Bedroom Thermostat
    unique_id: parents_bedroom_thermostat
    heater: switch.parents_bedroom_heating_valve
    target_sensor: sensor.parents_bedroom_thermometer_temperature
    heat_pump_cooling: binary_sensor.cooling_mode
```
