### ISSUE TITLE
Heating-cooling thermostat is off after restart

### ISSUE THREAD

**Issue by terba** [swingerman/ha-dual-smart-thermostat#386]
My thermostat with the following configuration are always off after a restart:
The ```heat_pump_cooling``` binary_sensor requires some time to get its value at restart (see the log lines below).

```yaml
- platform: dual_smart_thermostat
  name: Fsz. nappali termosztát
  unique_id: jwnqe5
  heater: input_boolean.fsz_nappali_termelesi_igeny
  heat_pump_cooling: binary_sensor.hutes
  target_sensor: sensor.nappali_homerseklet
  min_temp: 10
  max_temp: 30
  cold_tolerance: 0.3
  hot_tolerance: 0.3
  precision: 0.1
  target_temp_step: 0.5
```

The log contains the following after a restart:
```
2025-06-26 11:47:08.566 WARNING (MainThread) [custom_components.dual_smart_thermostat.hvac_device.heat_pump_device] Heat pump cooling entity state is unknown or unavailable: None
2025-06-26 11:47:15.072 WARNING (MainThread) [custom_components.dual_smart_thermostat.hvac_device.heat_pump_device] Heat pump cooling entity state is unknown or unavailable: <state binary_sensor.hutes=unknown; friendly_name=Hűtés @ 2025-06-26T11:47:15.015468+02:00>
```
