### ISSUE TITLE
Can I use this with thermostats instead of switches?

### ISSUE THREAD

**Issue by bbigras** [swingerman/ha-dual-smart-thermostat#39]
I'm assuming that ha-dual-smart-thermostat directly starts the heater and cooler.

I'm wondering if it could control thermostats for the heaters and coolers.

My use case is that I would like the AC to start when it's hot and the heat to start when it's cold, **but** not have them fight each others.

**Comment by skorpionwap** [comment]
This is exactly my case.  I use dual thermostat to control an AC.  This AC does not have a temperature sensor.  Dual Thermostat helps me to combine a temperature sensor with a virtual switch, to control the AC.  But this also involves automation.

**Comment by alvarocarrera** [comment]
I have the same setup: a heater/cooler AC, but I have solved this by defining a pair of switches like the followings for each AC in the HA configuration. Inside the general configuration.yaml, I added:
`
switch: !include switch.yaml                                                                                                      
`
and then, I created the switch.yaml file with a heater switch and a cooler switch for every AC.

The following example is for a room/climate named "oficina" (Office in Spanish):

```
# Switches (heater/cooler) for oficina:
- platform: template
  switches:
    oficina_heater:
      value_template: "{{ is_state('climate.termostato_de_la_oficina', 'heat') }}"
      turn_on:
        service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: 30
        target:
          entity_id: climate.termostato_de_la_oficina
      turn_off:
        service: climate.turn_off
        target:
          entity_id: climate.termostato_de_la_oficina
- platform: template
  switches:
    oficina_cooler:
      value_template: "{{ is_state('climate.termostato_de_la_oficina', 'cool') }}"
      turn_on:
        service: climate.set_temperature
        data:
          hvac_mode: cool
          temperature: 18
        target:
          entity_id: climate.termostato_de_la_oficina
      turn_off:
        service: climate.turn_off
        target:
          entity_id: climate.termostato_de_la_oficina
```

Then, you set up your dual_thermostat as:

```
- platform: dual_smart_thermostat
  name: Termostato Dual Oficina
  unique_id: termostato_dual_oficina
  heater: switch.oficina_heater
  cooler: switch.oficina_cooler
  target_sensor: sensor.termostato_de_la_oficina_temperature
  # the reminder options of the dual_thermostat
```
**Final note**: Even, you could specify a target temperature for the heater/cooler switch using a template (retrieving the target_temp of the dual_thermostat). But, in my case, as I turn on the AC in the cheapest hours of electricity cost, I want to boost the heating/cooling in those hours instead of "keeping the temperature around the target temp" all time. After those cheap hours, the zone is more heat/cool than the target temp, but it keeps at a comfortable temp for more time, trying to not use the AC during the expensive hours of electricity cost.

I hope this would have helped you. If you have any question about this setup, I can help you a bit more. :)
