### ISSUE TITLE
Developer tools - YAML configuration reloading makes current temperature "n/a"

### ISSUE THREAD

**Issue by paulius2k** [swingerman/ha-dual-smart-thermostat#42]
Hello,

my installation is:
```
Home Assistant 2022.11.4
Supervisor 2022.10.2
Operating System 9.0
Frontend 20221108.0 - latest
-
Home Assistant Dual Smart Thermostat component v0.7.1
```

This is my config:
```
climate:
  - platform: dual_smart_thermostat
    name: Test Fake Thermostat
    heater: switch.fake_thermostat_switch
    cooler: switch.fake_thermostat_switch
    target_sensor: sensor.sonoff_zb_temp1_temperature
    openings:
      - binary_sensor.sonoff_zb_ds2_ias_zone
    min_temp: 10
    max_temp: 28
    ac_mode: false
    target_temp: 20
    target_temp_high: 26
    target_temp_low: 19
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 15
      target_temp_low: 14
      target_temp_high: 16
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    precision: 0.1
    target_temp_step: 0.5
```

After reloading the component via "Developer tools - YAML configuration reloading - DUAL_SMART_THERMOSTAT", the current temp becomes n/a.

What fixes this:
- completely restarting HA,
- an update of temperature sensor. 

<img src="https://user-images.githubusercontent.com/24705262/203179742-c80622bb-3f8c-44ac-b80d-c1876a9f59f1.png" width=60%>
