### ISSUE TITLE
How to set time for openings in v0.9.0?

### ISSUE THREAD

**Issue by tianzhuang55** [swingerman/ha-dual-smart-thermostat#69]
Good news of the new feature on 0.9.0 to set a time for openings, however I check the full configuration example and still have no idea of how to set this open time value.

Could you please suggest? Thanks a lot! 

> Improvements
> feat: open time for openings by @swingerman in https://github.com/swingerman/ha-dual-smart-thermostat/pull/60
> You can now define a timeout for each opening by @swingerman in https://github.com/swingerman/ha-dual-smart-thermostat/pull/61

**Comment by swingerman** [comment]
@tianzhuang55 Added examples in [v0.9.1](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.1)

Example:

```yaml
openings:
  - sensor.window1
  - sensor.window2
  - entity_id: binary_sensor.window3
    timeout: 00:00:30 # cosnidered to be open if still open after 30 seconds
```
