### ISSUE TITLE
Invalid Config with 'heat_cool_mode'

### ISSUE THREAD

**Issue by mathmaniac43** [swingerman/ha-dual-smart-thermostat#72]
Hello,

I have used this thermostat with heating an cooling for a few months and it had been great. I wanted to tweak some config settings and am having the following error when I try to introduce 'heat_cool_mode' in my configuration.yaml. I am hoping I can get some help with this; maybe my syntax is wrong or I am missing something.

```
Invalid config for [climate.dual_smart_thermostat]: [heat_cool_mode] is an invalid option for [climate.dual_smart_thermostat]. Check: climate.dual_smart_thermostat->heat_cool_mode. (See ?, line ?).
```

My config is as follows (I commented out some settings to reduce variables).

```yaml
climate:                                                                                    # https://www.home-assistant.io/integrations/generic_thermostat
  - platform: dual_smart_thermostat
    name: Pool Hall Thermostat
    heater: switch.plug_e
    cooler: switch.plug_j_switch
    target_sensor: sensor.pool_hall_temperature
    heat_cool_mode: true
    #min_temp: 50
    #max_temp: 80
    #heat_cool_mode: true # @todo causes error?
    #target_temp_low: 50
    #target_temp_high: 80
    #min_cycle_duration:
    #  minutes: 10
```

I am using Home Assistant 2023.8.1 and Dual Thermostat 0.54.5.

Thanks!
Nick
