### ISSUE TITLE
Openings timeout not working

### ISSUE THREAD

**Issue by yordanov-alexandar** [swingerman/ha-dual-smart-thermostat#76]
I have configured the openings like this:
```
  openings:
    - entity_id: binary_sensor.bedroom_door
      timeout: 00:00:59
    - entity_id: binary_sensor.terrace_door
      timeout: 00:00:59
    - entity_id: binary_sensor.terrace_window
      timeout: 00:00:59
```
However as soon as I open one of the doors/windows the AC is turned off (there may be a delay of a few seconds but that is probably a delay of the sensor reading itself). The delay of 59 seconds is not taken into account.
Have I configured it wrong or is this a bug?

**Comment by mondomx** [comment]
I just ran into this same issue:

I have configured the openings with a 1 minute delay:

```
    openings:
    - entity_id: binary_sensor.openclose_11
      timeout: 00:01:00
    - entity_id: binary_sensor.openclose_13
      timeout: 00:01:00
    - entity_id: binary_sensor.openclose_14
      timeout: 00:01:00
    - entity_id: binary_sensor.openclose_15
      timeout: 00:01:00
```

However as soon as I open one of the doors/windows the AC is turned off. As per the documentation it says that the opening will need to remain open for however long the timeout parameter is configured before it turns off, but thats not how its working for me. 

Any ideas?
