### ISSUE TITLE
removing "target_temp_high" and/or "target_temp_low" from config removes "heat_cool" mode as well

### ISSUE THREAD

**Issue by paulius2k** [swingerman/ha-dual-smart-thermostat#77]
If I have this config for my thermostat:
```
  - platform: dual_smart_thermostat
    name: Test Fake Thermostat
    heater: switch.fake_thermostat_switch_heat_gpio27
    cooler: switch.fake_thermostat_switch_cool_gpio27
    target_sensor: sensor.sonoff_zb_temp1_temperature
    # floor_sensor: sensor.floor_temp
    # max_floor_temp: 28
    openings:
      - binary_sensor.sonoff_zb_ds2_ias_zone
    min_temp: 10
    max_temp: 28
    ac_mode: false # this parameter will be ignored if cooler entity is defined.
    target_temp: 20 # If this variable is not set, it will retain the target temperature set before restart if available.
    target_temp_high: 21
    target_temp_low: 20
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 1
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 15
      target_temp_low: 14
      target_temp_high: 16
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    precision: 0.1
    target_temp_step: 0.5
```

It has 4 `hvac_modes`:

```
hvac_modes: off, heat, cool, heat_cool
min_temp: 10
max_temp: 28
target_temp_step: 0.5
preset_modes: none, away
current_temperature: 22.9
hvac_action: idle
preset_mode: none
prev_target_temp_low: 20
prev_target_temp_high: 21
friendly_name: Test Fake Thermostat
supported_features: 18
target_temp_high: 21
target_temp_low: 20
prev_target_temp: 20
```

But if I remove any or all of these parameters:
```
    target_temp_high: 21
    target_temp_low: 20
```

then my thermostat loses `heat_cool` mode:
```
hvac_modes: off, heat, cool
min_temp: 10
max_temp: 28
target_temp_step: 0.5
preset_modes: none, away
current_temperature: 22.9
hvac_action: idle
preset_mode: none
friendly_name: Test Fake Thermostat
supported_features: 18
target_temp_high: 21
target_temp_low: 20
prev_target_temp_low: 20
prev_target_temp_high: 21
prev_target_temp: 20
```

Why is that?  
I'd like it to keep `heat_cool` mode and not reset to config target temps, instead retaining the previous UI values - just what the config functionality claims to do.

**Comment by mathmaniac43** [comment]
I get a warning of "Undefined target temperature, falling back to <temp>" every time HA restarts. I want it to remember the last min and max temps and just use them! In heat/cool mode, the SINGLE target temp should not be necessary either.

I am adding additional logic to store those values and persist across restarts. I really hope they can be handled by the integration someday soon. I am happy to help gather information and run experiments if that is helpful to diagnose and fix.

**Comment by swingerman** [comment]
For heat-cool mode
you need to set either:
```yaml
heat_cool_mode: true
```
or
```yaml
target_temp_low: ...
target_temp_high: ...
```

**Comment by mathmaniac43** [comment]
@swingerman Thanks for reaching back out.
I have tried using `heat_cool_mode: true` (see [this issue](https://github.com/swingerman/ha-dual-smart-thermostat/issues/72)),
but it causes an error.

**Comment by paulius2k** [comment]
@swingerman thank you - it does work if I set "heat_cool_mode: true", not sure how I missed that earlier. thank you.

**Comment by mathmaniac43** [comment]
@paulius2k Would you share your final working config? I am not sure why mine is causing that error,
and last time I looked into this, I tried every combination I could think of...

**Comment by paulius2k** [comment]
@mathmaniac43 - here is my working config:
```
  - platform: dual_smart_thermostat
    name: Test Fake Thermostat
    heater: switch.fake_thermostat_switch_heat_gpio27
    cooler: switch.fake_thermostat_switch_cool_gpio27
    target_sensor: sensor.sonoff_zb_temp1_temperature
    openings:
      - binary_sensor.sonoff_zb_ds2_ias_zone
    min_temp: 10
    max_temp: 28
    ac_mode: false # this parameter will be ignored if cooler entity is defined.
    heat_cool_mode: true
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 1
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 15
      target_temp_low: 14
      target_temp_high: 16
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    precision: 0.1
    target_temp_step: 0.5
```
