### ISSUE TITLE
preset mode being set on wrong entity

### ISSUE THREAD

**Issue by mbrevda** [swingerman/ha-dual-smart-thermostat#80]
Hi - got a strange issue here. Looks like my preset modes are being set on the wrong entity.  Notice how the "Dining Room" has two preset modes - and the boys room has none. I'm seeing this in other entities, too.
<img width="1014" alt="Screenshot 2023-10-17 at 9 44 37 AM" src="https://github.com/swingerman/ha-dual-smart-thermostat/assets/293004/40bfa655-4126-4d2e-8394-6757214bc07e">

Here is the configuration for these two:

```yaml
- platform: dual_smart_thermostat
  name: Boys Room
  heater: switch.boys_room_radiator
  cooler: switch.boys_room_air_conditioner
  target_sensor: sensor.boys_room_temperature_temperature
  min_cycle_duration: 60
  precision: .5
  min_temp: 20
  max_temp: 25
  heat_cool_mode: true
  away:
    temperature: 30
    target_temp_low: 50
    target_temp_high: 0

- platform: dual_smart_thermostat
  name: Dining Room
  heater: switch.dining_room_radiator
  target_sensor: sensor.dining_room_thermostat_temperature
  min_cycle_duration: 60
  precision: .5
  min_temp: 20
  max_temp: 25
  away:
    temperature: 15

```

Is this something on my end? Thanks!
