### ISSUE TITLE
sleep mode dont pass configuration.yaml.

### ISSUE THREAD

**Issue by haute12345** [swingerman/ha-dual-smart-thermostat#85]
i can define all modes:
```
away: # this preset will be available for all hvac modes
      temperature: 13
      target_temp_low: 12
      target_temp_high: 14
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    comfort:
      temperature: 22
    eco:
      temperature: 19
    away:
      temperature: 17
    #sleep:
    #  temperature: 19
```
but if configure sleep mode, HA show error for sleep mode.
