### ISSUE TITLE
Keep_alive not working

### ISSUE THREAD

**Issue by HappyPlotter** [swingerman/ha-dual-smart-thermostat#91]
I have set the thermostat with keep_alive to control a shelly device. On the shelly I have set a timeout of 10 minutes and the keep_alive is set to 1 minute. The shelly device turns off after 10 minutes and then immediately turns on again. It seems like the keep_alive is not working which makes the heater cycle every 10 minutes
```
climate:
  - platform: dual_smart_thermostat
    name: House Underfloor Heater
    heater: switch.heater
    target_sensor: sensor.floor_temperature
    openings:
      - entity_id: binary_sensor.balcony_window
        timeout: 00:02:00
      - entity_id: binary_sensor.house_entrance_door
        timeout: 00:02:00
      - entity_id: binary_sensor.living_room_right_window
        timeout: 00:02:00
      - entity_id: binary_sensor.living_room_left_window
        timeout: 00:02:00
    min_temp: 16
    max_temp: 31
    precision: 0.1
    target_temp_step: 0.5    
    cold_tolerance: 0.1
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 10
    away_temp: 19
    home_temp: 20
    comfort_temp: 21
    keep_alive: 60
```
